<?php

namespace App\Lib;

use Illuminate\Support\Facades\DB;

class CustomDB extends DB
{
    private Pager $pager;

//    public static function table(string $table, string $as = null): \Illuminate\Database\Query\Builder
//    {
//        parent::table($table, $as); // TODO: Change the autogenerated stub
//    }

    public function withPager(Pager $pager)
    {
        $this->pager = $pager;
    }
}
